kmeans:
  num_centroids: 10
  random_state: 42
  max_pixels_for_fit: 1000000
  centroids:
  - - 68.44047546386719
    - 69.09268188476562
    - 61.156394958496094
  - - 232.72401428222656
    - 235.21270751953125
    - 235.4442138671875
  - - 144.073974609375
    - 176.44894409179688
    - 208.87435913085938
  - - 30.50492286682129
    - 28.23670768737793
    - 25.139352798461914
  - - 149.05686950683594
    - 149.0969696044922
    - 144.07386779785156
  - - 172.54708862304688
    - 145.5629425048828
    - 96.06011962890625
  - - 74.07644653320312
    - 112.89799499511719
    - 153.32568359375
  - - 122.26431274414062
    - 87.8080062866211
    - 54.235233306884766
  - - 112.38972473144531
    - 112.59928131103516
    - 99.2037124633789
  - - 196.50741577148438
    - 190.32005310058594
    - 178.6128692626953
filter_bank:
  per_channel: true
  padding: reflect
  processing_batch_size: 64
  n_jobs: -1
  gaussian:
    sigmas:
    - 1.0
    - 2.0
  laplacian:
    sigmas:
    - null
    - 1.5
  gabor:
    num_thetas: 6
    lambd: 8.0
binarizer:
  fit_sample_size: 10000
  thresholds_filters:
  - - 73.40751495361329
    - 108.33050231933593
    - 139.73806762695312
    - 176.92569274902343
  - - 71.7243865966797
    - 105.13430938720703
    - 135.74095764160154
    - 173.17835083007813
  - - 57.41164779663087
    - 88.96132965087891
    - 123.39974517822264
    - 171.2407257080078
  - - 79.28410339355469
    - 110.26659088134765
    - 137.90171203613278
    - 171.01082458496094
  - - 77.23319854736329
    - 106.88272552490234
    - 133.87487182617184
    - 167.51539916992186
  - - 62.45402145385742
    - 91.42385864257812
    - 122.24719848632812
    - 165.1576629638672
  - - -27.0
    - -4.0
    - 4.0
    - 27.0
  - - -27.0
    - -4.0
    - 4.0
    - 27.0
  - - -26.0
    - -4.0
    - 4.0
    - 26.0
  - - -37.83761215209961
    - -7.931629848480222
    - 7.418336677551261
    - 37.65088958740235
  - - -36.8228515625
    - -7.759213066101073
    - 6.911749458312979
    - 36.68307189941406
  - - -35.2255256652832
    - -6.740974426269531
    - 7.0925277709960906
    - 35.39361648559571
  - - -4.2388818740844725
    - -0.953399395942688
    - 0.9440584063529968
    - 4.25037784576416
  - - -4.157391166687011
    - -0.9212438583374023
    - 0.9276818990707387
    - 4.194427585601806
  - - -4.007173728942871
    - -0.8803326487541198
    - 0.8815191030502318
    - 4.0224623680114755
  - - -3.453501510620117
    - -0.7868890404701232
    - 0.7815036773681638
    - 3.4589794158935545
  - - -3.377272891998291
    - -0.761645436286926
    - 0.7662834048271174
    - 3.388135004043579
  - - -3.2594754695892334
    - -0.7296727776527404
    - 0.7253027915954586
    - 3.252322578430176
  - - -3.946463394165039
    - -0.949022078514099
    - 0.9656059384346007
    - 3.9815989971160897
  - - -3.8177620410919184
    - -0.9158474206924438
    - 0.9388536214828476
    - 3.87331109046936
  - - -3.6957681655883787
    - -0.8796035766601562
    - 0.8812163710594172
    - 3.7401552677154544
  - - -5.545100688934326
    - -1.2878833293914793
    - 1.2923275232315055
    - 5.601674842834473
  - - -5.341421222686767
    - -1.2388252019882202
    - 1.2478302001953123
    - 5.413508224487305
  - - -5.153442001342773
    - -1.1757134199142456
    - 1.1720667839050292
    - 5.212194538116455
  - - -3.915417623519897
    - -0.9483698725700376
    - 0.959348392486572
    - 3.957989740371705
  - - -3.798759889602661
    - -0.911910891532898
    - 0.9374855995178217
    - 3.8527203083038333
  - - -3.6735803127288817
    - -0.87461256980896
    - 0.8751882672309872
    - 3.722022771835327
  - - -3.4575612545013428
    - -0.7866077542304992
    - 0.7837181448936458
    - 3.4657281875610364
  - - -3.3857760429382324
    - -0.7646948814392089
    - 0.769379365444183
    - 3.403791427612305
  - - -3.271002912521362
    - -0.7361279606819151
    - 0.7255956888198841
    - 3.2685805320739747
  thresholds_kmeans:
  - - 45.38939666748047
    - 79.75086975097656
    - 124.9771957397461
    - 194.55523681640625
  - - 106.66770935058594
    - 178.8441162109375
    - 236.04339599609375
    - 295.44500732421875
  - - 75.982421875
    - 113.28692169189453
    - 151.02410888671875
    - 204.79141235351562
  - - 69.94735717773438
    - 131.10020446777344
    - 188.46536865234373
    - 259.598583984375
  - - 49.84366226196289
    - 80.95117950439453
    - 115.49240570068358
    - 159.5681915283203
  - - 61.07839584350586
    - 89.26306610107423
    - 121.39395141601562
    - 162.01454162597656
  - - 77.0267562866211
    - 100.33897399902344
    - 124.49193572998047
    - 159.281494140625
  - - 54.647987365722656
    - 80.84217071533203
    - 114.13028717041016
    - 164.6806182861328
  - - 43.62871551513672
    - 70.97358703613281
    - 102.70054779052728
    - 145.8277435302735
  - - 63.5745735168457
    - 108.2504653930664
    - 157.62905883789062
    - 216.27381896972656
